#!/bin/env bash

# Opciones del menú de energía con iconos
lock=""
logout=""
shutdown=""
reboot=""
sleep=""

# Mostrar el menú con rofi
selected_option=$(echo "$lock
$logout
$sleep
$reboot
$shutdown" | rofi -dmenu \
                  -i \
                  -p "Power" \
                  -theme "~/.config/rofi/themes/powermenu-theme.rasi")

# Ejecutar acción según la opción seleccionada
case "$selected_option" in
    "$lock")
        betterlockscreen -l blur 0.5
        ;;
    "$logout")
        i3-msg exit
        ;;
    "$shutdown")
        i3-msg exec doas poweroff
        ;;
    "$reboot")
        i3-msg exec doas reboot
        ;;
    "$sleep")
        i3-msg exec doas systemctl suspend
        ;;
    *)
        echo "Sin coincidencias"
        ;;
esac

